### ISSUE TITLE
Livraison immédiate > Produit shortpye / réf 1523 > prix dans la mauvaise grille tarifaire : les prix sont initialement de 9$ et 8¥, aucun prix dans colonne €. Après migration, cela affiche 9€, 8¥ et aucun prix en $

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#10]
Livraison immédiate > Produit shortpye / réf 1523 > prix dans la mauvaise grille tarifaire : les prix sont initialement de 9$ et 8¥, aucun prix dans colonne €. Après migration, cela affiche 9€, 8¥ et aucun prix en $

A voir avec Ludovic

**Comment by AndOrStudio** [comment]
Problème d'affichage de notre coté, on règle ça
