### ISSUE TITLE
Agents migrés dans Users 

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/play-migration-v1-v2#19]
Les agents ont été migrés en tant que ""users"" (utilisateurs du compte) en plus d'être dans Réseau
https://drive.google.com/file/d/0B9Zmb2lmy-4lOUZpQTlFZXByQzA/view

**Comment by mikael-desharnais** [comment]
Comme dans la V1, les agents sont d"abord des users. Peut-être y a t'il un champ à remplir pour éviter que les agents n'apparaissent pas. Demander à Ludovic sur ce point

**Comment by AndOrStudio** [comment]
Des user oui, mais pas des brand_user, les agents ne doivent pas etre dans brand_user mais dans user et brand_agent

**Comment by mikael-desharnais** [comment]
Ce point a été corrigé
