### ISSUE TITLE
Prévisualisation de fiche article : bug

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/play-migration-v1-v2#24]
https://drive.google.com/file/d/0B9Zmb2lmy-4lZTJua0tWdm1QQzQ/view

**Comment by mikael-desharnais** [comment]
Le code appelé :
http://preprod2.playologie.com/api/buyerbrandcollectionproduct/product/?id_product=10301
plante car il n'y a pas de prix dans la monnaie définie pour l'acheteur. Ce cas n'est pas un problème de remplissage de BDD mais un problème de code.
