### ISSUE TITLE
Tous les articles affichent le picto bio

### ISSUE THREAD

**Issue by Playologie** [thibaultvanc/play-migration-v1-v2#25]
Dans leur fiche article il y a un bien des articles non bio (bien migré) mais à l'affichage de la collection le picto bio s'affiche chez tous les articles.
https://drive.google.com/file/d/0B9Zmb2lmy-4lU1BBVVhYNFg5Tlk/view

**Comment by mikael-desharnais** [comment]
Il s'agit d'un bug dans le code, pour ne prendre que l'exemple de la référence 23598, le champs is_bio est bien à 0.
