### ISSUE TITLE
Aucune marque ne s'affiche dans l'admin (connecté avec manager@playologie.com) 

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#29]
-> ludovic indique que c'est parce que les marques n'ont pas de 'brand_user' de type owner

**Comment by thibaultvanc** [comment]
il y beaucoup de brand_user de type owner et quelqu'un de type de user, à peut près 1100 de type owner et 10 de type user

**Comment by AndOrStudio** [comment]
Et donc ? Le fait qu'il y en ai beaucoup ne veut pas dire qu'il en manque pas pour une marque donnée je crois ?

**Comment by thibaultvanc** [comment]
Ludovic, merci de nous donner plus d'information SVP

**Comment by AndOrStudio** [comment]
Il ne me semble pas que ça soit très compliqué d'aller checker quel brand n'ont pas de brand_user de type owner mais je vous le fait pour cette fois, il y en a une dizaine :

[{
	"brand": {
		"id_brand": 127,
		"id_address": 1,
		"name": "Mon Marcel",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-30 15:29:35",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 130,
		"id_address": 1,
		"name": "Coq en pâte",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-20 15:14:12",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 131,
		"id_address": 1,
		"name": "Coq en pâte",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-20 15:14:12",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 132,
		"id_address": 1,
		"name": "Coq en pâte",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-20 15:14:12",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 133,
		"id_address": 1,
		"name": "Coq en pâte",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-20 15:14:12",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 134,
		"id_address": 1,
		"name": "Coq en pâte",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-20 15:14:12",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 144,
		"id_address": 1,
		"name": "Play ",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2014-06-25 08:26:59",
		"updated_at": "2016-01-22 18:16:51"
	}
}, {
	"brand": {
		"id_brand": 337,
		"id_address": 1,
		"name": "Ma petite Anglaise",
		"file_logo": "55c0dfb40bb8f.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1422287599,
		"sub_start_date": "2015-01-26 15:53:19",
		"sub_end_date": 1453507200,
		"status": 1,
		"created_at": "2015-01-22 11:05:44",
		"updated_at": "2016-12-19 20:55:18"
	}
}, {
	"brand": {
		"id_brand": 392,
		"id_address": 1,
		"name": "Waddler",
		"file_logo": "5698ff7f19380.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1424131200,
		"sub_start_date": "2015-02-17 00:00:00",
		"sub_end_date": 1455667200,
		"status": 1,
		"created_at": "2014-11-03 14:11:47",
		"updated_at": "2016-12-19 20:55:18"
	}
}, {
	"brand": {
		"id_brand": 393,
		"id_address": 1,
		"name": "Velveteen'",
		"file_logo": "5649a039df794.png",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1424131200,
		"sub_start_date": "2015-02-17 00:00:00",
		"sub_end_date": 1455667200,
		"status": 1,
		"created_at": "2014-06-20 07:15:51",
		"updated_at": "2016-12-19 20:55:18"
	}
}, {
	"brand": {
		"id_brand": 503,
		"id_address": 1,
		"name": "Pop Cutie",
		"file_logo": "55ca11763c91a.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1432771200,
		"sub_start_date": "2015-05-28 00:00:00",
		"sub_end_date": 1467158400,
		"status": 1,
		"created_at": "2015-05-28 19:48:22",
		"updated_at": "2016-12-19 20:55:18"
	}
}, {
	"brand": {
		"id_brand": 628,
		"id_address": 1,
		"name": "Designskin Europe",
		"file_logo": "55cb150e9d23d.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1439228401,
		"sub_start_date": "2015-08-10 17:40:01",
		"sub_end_date": 1481328000,
		"status": 1,
		"created_at": "2015-07-30 20:25:46",
		"updated_at": "2016-12-19 20:55:18"
	}
}, {
	"brand": {
		"id_brand": 868,
		"id_address": 1,
		"name": "KidsBrand",
		"file_logo": "56000897e9d4a.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1459351892,
		"sub_start_date": "2016-03-30 15:31:32",
		"sub_end_date": -62169984000,
		"status": 1,
		"created_at": "2015-06-12 12:08:02",
		"updated_at": "2016-12-19 20:55:19"
	}
}, {
	"brand": {
		"id_brand": 869,
		"id_address": 1,
		"name": "MaternityBrand",
		"file_logo": "5600093738fe4.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1459351830,
		"sub_start_date": "2016-03-30 15:30:30",
		"sub_end_date": -62169984000,
		"status": 1,
		"created_at": "2015-06-12 12:14:54",
		"updated_at": "2016-12-19 20:55:19"
	}
}, {
	"brand": {
		"id_brand": 870,
		"id_address": 1,
		"name": "HomeBrand",
		"file_logo": "560008467a471.jpg",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": 1459351854,
		"sub_start_date": "2016-03-30 15:30:54",
		"sub_end_date": -62169984000,
		"status": 1,
		"created_at": "2015-06-12 12:12:05",
		"updated_at": "2016-12-19 20:55:19"
	}
}, {
	"brand": {
		"id_brand": 961,
		"id_address": 1,
		"name": "playkid",
		"file_logo": "",
		"playologie_comment": "",
		"registration_comment": "",
		"member_date": false,
		"sub_start_date": null,
		"sub_end_date": null,
		"status": 1,
		"created_at": "2016-05-26 17:46:28",
		"updated_at": "2016-06-28 11:13:36"
	}
}]
