### ISSUE TITLE
Livraison immédiate > Paramètres : le délai de traitement  : "up to 2 months "

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#3]
Livraison immédiate > Paramètres : le délai de traitement de commande n'a pas été récupéré : "up to 2 months "

**Comment by thibaultvanc** [comment]
L'ancien champ était une chaine de caractère "Up to 2 months" dans ce cas. Le nouveau est un entier ..., il est impossible de faire correspondre ces deux informations

**Comment by AndOrStudio** [comment]
Pas de solution de mon coté, Schlomi a spécifié un int de notre coté et tout est codé là dessus

**Comment by thibaultvanc** [comment]
OK il nous faut connaître la correspondance de cet integer

**Comment by mikael-desharnais** [comment]
Ok modifié
