### ISSUE TITLE
Livraison immédiate > Produit shortpye > n'affiche pas 3 paramètres produit : filtres Fille/Garçon, tranche d'age 

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#5]
Livraison immédiate > Produit shortpye / réf 1523 > la section "Classification" n'affiche pas 3 paramètres produit : filtres Fille/Garçon, tranche d'age (on coche les 3 par défaut) et Style (rien à migrer)

**Comment by thibaultvanc** [comment]
Dans la table brand_collection_product_feature

**Comment by thibaultvanc** [comment]
Ok les données sont bonnes mais je ne vois rien apparaître : PB CODE

**Comment by AndOrStudio** [comment]
Problème de bdd, c'est les id 5/6/7 qui sont associé à ce produit alors que ça devrait être 4/5 donc c'est un problème d'association de votre coté, migration à revoir.
