### ISSUE TITLE
Les tailles n'ont pas été créées

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#6]
Les tailles n'ont pas été créées. En V1 des tailles pouvaient être en dehors d'une "groupe de prix". Il faut dans ce cas les mettre dans un premier groupe par défaut. Les groupes de prix ont bien été migrés, mais ne contiennent aucune taille en V2
- Etrangemment, l'article ID=8697 basé sur la grille de tailles "Children", affiche bien ces tailes dans l'édition de l'article
Dans la rubrique Sizes de la V2 cette grille est vide 
- De son coté l'article ID=15570 basé sur la grille de tailles "Baby" n'affiche aucune taille dans l'édition de la fiche produit ET la grille est vide dans Sizes

**Comment by thibaultvanc** [comment]
PB CODE : la base de donnée est OK : il y a parfois des tailles et un nombre plus réduit est affiché et les tailles affichées n'ont pas de nom alors qu'elles en ont un en base ...

**Comment by thibaultvanc** [comment]
Je ne comprends pas la table brand_price.
La table brand_price_group affecte un size group à chaque price_group.
La table brand_price semble relier les price groups et les tailles.

**Comment by thibaultvanc** [comment]
Pourquoi selon vous les tailles s'affichent mal dans les grilles ?

**Comment by thibaultvanc** [comment]
La table PLAY_brand_price n'est pas instancié, il faut y associer le price créé au price_group créé, ce qui n'est pas le cas
Aussi, plusieurs price_group vide ont été créé lors de la migration, à revoir du coté du script mais la BDD n'est pas bonne

**Comment by thibaultvanc** [comment]
Je ne comprends pas la table brand_price.
La table brand_price_group affecte un size group à chaque price_group.
La table brand_price semble relier les price groups et les tailles.

**Comment by AndOrStudio** [comment]
C'est le cas et c'est ce qu'il manque dans la migration actuelle, l'association des taille au groupe de saisie de prix

**Comment by mikael-desharnais** [comment]
Ok modifié
Si les tailles n'ont pas de price group, un price group est crée avec le nom default.
