### ISSUE TITLE
Le "sales manager" associé à cette commande est Sophie Marius. La V2 n'a pas récupéré cette donnée

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#7]
Le "sales manager" associé à cette commande est Sophie Marius. La V2 n'a pas récupéré cette donnée

**Comment by thibaultvanc** [comment]
Pourquoi les sales manager associé ne s'affiche pas

-> Ce brand_user n'a pas le flag is_sales_manager égale à 1

**Comment by thibaultvanc** [comment]
Dans la V1, le brand_user 1028 (id_user=5459), n'est pas sales manager (vue dans brands_users_rights) ...
Le fait de forcer ce flag à 1 pour que cela apparaisse dans une commande n'est pas une bonne idée car si à un instant T, une personne est définie comme sales manager, que des commandes sont passées à T+1 et qu'à T+2, la personne se voit retirer son status de sales manager, alors la commande sera modifiée ...

**Comment by AndOrStudio** [comment]
Le brand_user n'est plus éditable lorsque la commande est validée (de mémoire), cette problématique évoquée n'est vrai que pour une commande en cours d'édition et ce n'est donc pas un problème en soit

**Comment by mikael-desharnais** [comment]
Ludovic a bien compris la problématique et doit voir avec le client comment gérer ça puisque la base est OK.
