### ISSUE TITLE
Problème : les couleurs ou imprimés ne sont pas migrés et donc absents dans la saisie des stocks

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#8]
Problème : les couleurs ou imprimés ne sont pas migrés et donc absents dans la saisie des stocks

**Comment by thibaultvanc** [comment]
aucun produit ne s'affiche car il faut que ce stock soit lié à la plateforme par défaut (il y en a forcément une mondiale). Chaque marque possède une plateforme de stock unique par défaut avec tous les pays du monde. Et le stock migré fait partie de cette plateforme

**Comment by thibaultvanc** [comment]
La plateforme a bien été crée, la base est OK, s'il y a un soucis, il vient du code

**Comment by AndOrStudio** [comment]
Et il reste un soucis ?

**Comment by mikael-desharnais** [comment]
Ce ticket serait-il un doublon du 22 ?
