### ISSUE TITLE
Livraison immédiate > Paramètres > liste des agents : icone "terre" : les pays attribués à l'agent ne s'affichent pas dans la pop-in (+ bouton clos inopérant)

### ISSUE THREAD

**Issue by thibaultvanc** [thibaultvanc/play-migration-v1-v2#9]
Livraison immédiate > Paramètres > liste des agents : icone "terre" : les pays attribués à l'agent ne s'affichent pas dans la pop-in (+ bouton clos inopérant)

"Agents migrés ,mais pays vides 
J'ai migré les informations disponibles dans la table brands_users_available_countries mais il est vrai qu'il y a aussi un champ dans la table brands_users qui se nomme available countries et available_states, savez lequel de ces deux champs est le bon ?

brands_users > available countries = les pays accordés à l’agent brands_users > available_states = utilisé que pour les USA car pour un Agent à qui on attribue les USA, on peut aller un niveau plus bas et lui attribuer tout ou partie des états américains"

**Comment by thibaultvanc** [comment]
Ok les pays sont migrés, la base de donnée est OK mais le code doit pas convenir

**Comment by AndOrStudio** [comment]
C'est bien de notre coté, en dehors du fait que les clés region en sont pas bonne, voir autre issue
